### ISSUE TITLE
Crash calling to_Image() on graphics lump objects

### ISSUE THREAD

**Issue by JPLeBreton** [devinacker/omgifol#12]
This code:

```
import omg
w = omg.WAD()
w.from_file('doom.wad')
img = w.sprites['HEADA1'].to_Image()
```

produces this error:

```
Traceback (most recent call last):
  File "image_error.py", line 6, in <module>
    img = w.sprites['HEADA1'].to_Image()
  File "omg/lump.py", line 169, in to_Image
    im.fromstring(self.to_raw())
  File "omg/lump.py", line 151, in to_raw
    pointers = unpack('%il'%width, data[8 : 8 + width*4])
struct.error: unpack requires a string argument of length 504
```

Happens with every graphics lump I try in a wad.

Running omgifol from Arch Linux, Python 2.7.11 with PIL version 1.1.7 (Pillow version 3.2.0)

**Comment by devinacker** [comment]
Is this also with the python3 branch, or master?

(the former is a work-in-progress attempt at making the package compatible with both python 2 and 3, which I've been kind of neglecting; I had wanted to eventually merge the branch back into master once it was stable. Thanks for giving it a bit more testing - I'll look at both issues soon)

**Comment by JPLeBreton** [comment]
Ah yes, I should have specified that this is with the master branch and Python2.

**Comment by devinacker** [comment]
OK, found the issue - python on your system treats longs as 8 bytes rather than 4, which is the size that `omg.Graphic.to_raw` expects it to be when decoding the lump.

Rather than fixing this specific case just yet, I'd like to go through and make sure every call to `struct.unpack` is sufficiently strict about size/endianness, but in the meantime you can change the format string on L151 of lump.py to `'<%il'` which should be enough to fix exporting images.

**Comment by devinacker** [comment]
Should be better in 301ca31daf69b154db323804472cdf7bbade6e4c, give it a try.
