### ISSUE TITLE
omg.WAD should support reading from read-only WAD files.

### ISSUE THREAD

**Issue by selliott512** [devinacker/omgifol#24]
Currently calling WAD.from_file() on a read-only WAD file fails:
```
  File "/usr/lib/python2.7/site-packages/omg/wad.py", line 256, in from_file
    w = WadIO(source)
  File "/usr/lib/python2.7/site-packages/omg/wadio.py", line 75, in __init__
    self.open(openfrom)
  File "/usr/lib/python2.7/site-packages/omg/wadio.py", line 88, in open
    self.basefile = open(filename, 'r+b')
IOError: [Errno 13] Permission denied: '/usr/share/doom/freedoom2.wad'
```
As can be seen at the end of the callstack the file is opened 'r+b', which is read and write.

This is unfortunate in my case since I'm only interested in examining/reading a WAD file. To work around it I copy the WAD to a temporary directory, open that, and then delete it on exit.

I keep my WADs read-only so they are not accidentally modified. Perhaps other people do too, or they should.

Also, WAD.to_file() makes me think there is no need for need for WAD.from_file() to open the file read/write.

**Comment by devinacker** [comment]
The WadIO opens files in `r+b` mode since it has several methods which write directly to an already-open WAD. WAD.from_file and to_file don't use any of these, but an application or user might find them useful for more advanced WAD file management.

Anyway, I changed WadIO.open to be able to fall back to opening a file in read-only mode if needed.
