### ISSUE TITLE
Discrepancy between same map data pre-and-post to_lumps

### ISSUE THREAD

**Issue by JPLeBreton** [devinacker/omgifol#25]
WadSmoosh uses omgifol for all its heavy lifting, and I've noticed that the map WADs I extract (from the source IWADs) using it don't end up with the same "map MD5 sums" that GZDoom et al expect for detecting and applying the map fixes specified in its internal data. I'd much rather let GZDoom apply its fixes than add lots of custom fix code to WadSmoosh.

According to its code, each entry in GZDoom's compatibility.txt is an MD5 sum of the map's "header, THINGS, LINEDEFS, SIDEDEFS, SECTORS, and BEHAVIOR lumps". When I try "mapchecksum e3m4" for the omgifol-extracted version versus the doom.wad version, I do indeed get a different result.

The WadSmoosh code for extracting a map from an IWAD looks like this:
```
def extract_map(in_wad, map_name, out_filename):
    out_wad = omg.WAD()
    ed = omg.MapEditor(in_wad.maps[map_name])
    out_wad.maps[map_name] = ed.to_lumps()
    out_wad.to_file(out_filename)
```
So it seems like something MapEditor.to_lumps() does introduces a change from the input data.
Bug, or feature?

**Comment by devinacker** [comment]
Back when I was first adding Python 3 support, I had to deal with cases where some IWAD maps had garbage following the ending null bytes in sidedef texture names. It's possible/likely that the only reason the MD5s differ after saving is because MapEditor removes these at load time.

I'm not really sure if there's a very good way to account for those cases that doesn't affect the MD5 of a map, though. It's kind of unfortunate that the sums can end up being affected by something that is totally invisible to the user and liable to be silently removed by WAD editing tools.

**Comment by JPLeBreton** [comment]
Hmm. All I need out of omgifol in this case is to copy the map lumps' data directly into a new standalone file, is there a way to do that that doesn't even involve creating a MapEditor?

**Comment by devinacker** [comment]
In that case, you can just put a shallow copy of the map's lumps into a new omg.WAD instance and save that, i.e.:

```
src  = omg.WAD("doom.wad")
dest = omg.WAD()

dest.maps['E1M1'] = src.maps['E1M1']
dest.to_file("e1m1.wad")
```

This creates a new WAD with a byte-for-byte identical map to the source and is probably also significantly faster than having to parse and save all the map data each time.

**Comment by JPLeBreton** [comment]
This works great, thanks very much. Feel free to close this as WONTFIX or whatever's appropriate.
