### ISSUE TITLE
complains about missing SECTORS lump, but it's there

### ISSUE THREAD

**Issue by jmtd** [devinacker/omgifol#34]
This can be avoided by building nodes and adding the derivative lumps

```
▶ lswad trivial.wad
  name  	  size  	 offset 
MAP01   	0       	12
THINGS  	10      	12
LINEDEFS	56      	22
SIDEDEFS	120     	78
VERTEXES	16      	198
SECTORS 	26      	214
WADCSRC 	113     	240
▶ cat bug1.py
import sys
from omg import *
from omg.mapedit import *
inwad= WAD()
inwad.from_file(sys.argv[1])
ed = MapEditor(inwad.maps['MAP01'])
▶ python bug1.py trivial.wad
Traceback (most recent call last):
  File "bug1.py", line 6, in <module>
    ed = MapEditor(inwad.maps['MAP01'])
  File "/home/jon/git/doom/omgifol/omg/mapedit.py", line 180, in __init__
    self.from_lumps(from_lumps)
  File "/home/jon/git/doom/omgifol/omg/mapedit.py", line 234, in from_lumps
    raise ValueError("map is missing %s lump" % e)
ValueError: map is missing 'SECTORS' lump
```

[trivial.zip](https://github.com/devinacker/omgifol/files/3151750/trivial.zip)

**Comment by devinacker** [comment]
Pretty sure this is a(n unintended) consequence of the change made in bb6dd5ff934cba6f28a1cd40d97be33edbf91420, which was meant to make sure that all of the individual map lumps (including nodes) are present in the correct order when detecting maps, due to some non-map lumps getting falsely categorized as maps in certain (rare) cases.

Not sure what would be the best way to handle maps with missing nodes without also breaking those cases again... I'll have to think about it a bit.

**Comment by jmtd** [comment]
> Pretty sure this is a(n unintended) consequence of the change made in bb6dd5f

Good catch, I can confirm at least that reverting that change prevents this particular issue. Not suggesting you should revert in the repo though.

**Comment by devinacker** [comment]
Try merging the most recent commit and see if that helps. I mostly reverted the aforementioned commit but adjusted the old behavior to hopefully avoid the same false positives.

**Comment by jmtd** [comment]
Yep that's sorted now thanks
