### ISSUE TITLE
Putting omgifol on pypi?

### ISSUE THREAD

**Issue by jmickle66666666** [devinacker/omgifol#9]
Has this been considered yet? It would help with keeping it up to date for users, meaning avoiding issues like Linguica's, using old versions like fredrikj's latest update.

**Comment by devinacker** [comment]
(continuing from what I said on IRC the other day)

This'll probably be done at some point. I originally started this fork for my own personal use but it'd be nice to have an official package distribution now that people seem to be using it more.

Since putting it on pypi would probably make me the de facto "official" maintainer of omgifol (if I wasn't already) I'd at least like to get @fredrik-johansson's blessing first.

Other stuff that I'd probably like to be done first:
- bump the version number to make sure it's considered distinct from Fredrik's last version
- ensure the entire package is compatible with Python 3
- make some of the changes to MapEditor you had mentioned on IRC
- update (or at least note) stuff relating to limit-removing maps and other basic source port features that aren't supported yet (MapEditor can read limit-removing and Hexen/ZDoom maps now but there's probably still useful stuff missing for those)

Feel free to mention anything else you think would be good to include in a "0.3" release.

In the longer term I'd also like to expand the Doom 64 map support (which is currently in the doom64 branch but isn't very robust).

**Comment by devinacker** [comment]
Also, the new "python3" branch is exactly what it sounds like. This branch _should_ work with both 2.7 and 3.x at this point (at least the demo scripts and my own scripts do). I suspect omg.util might need a bit more fixing up now (or at least docstring updates)

**Comment by fredrik-johansson** [comment]
Please go ahead!

Before putting it on pypi, I think it really needs to be converted to a proper Python package, with a setup.py and so on.

**Comment by devinacker** [comment]
Yeah, I plan to do that as well when it's ready. Thanks!

**Comment by devinacker** [comment]
https://pypi.python.org/pypi/omgifol/0.3.0

At last, you can `pip install omgifol` :) I also decided to tag this as a new release since I don't think there was anything else important that I hadn't taken care of yet.

This is my first time publishing a real Python package so let me know if I screwed something up.

**Comment by fredrik-johansson** [comment]
Cool, thanks!
